apiVersion: v1
kind: Service
metadata:
  name: nginx-node
  namespace: roboshop
spec:
  type: NodePort
  selector:
    project: roboshop
    environment: dev
  ports:
  - protocol:
    port: 80
    targetPort: 80