apiVersion: v1
kind: Service
metadata:
  name: demo-nodeport
  namespace: roboshop
spec:
  type: NodePort
  selector:
    project: roboshop
    environment: dev
  port:
  - protocol: TCP
    port: 80 #serviceport
    targetPort: 80  #containerport