apiVersion: v1
kind: Pod
metadata:
  name: replica-demo
  labels:
    project: roboshop
    environment: dev
    tier: frontend
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
         labels:
          project: roboshop
          environment: dev
          tier: frontend
          component: frontend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: frontend
        component: frontend

    spec:
      containers:
      - name: nginx
        image: nginx